### ISSUE TITLE
Unable to register components

### ISSUE THREAD

**Issue by Ketcap** [makeswift/makeswift#108]
While using the defined browsers below: If I preview the page for registering components and checking it, it does not register and does not throw an error. Found out browsers that are mentioned are blocking "postMessage" API from browsers.
Attached are screenshots showing registering components are not even imported, you can see the "hello world" console log is not called when Brave's shield is active and safari fails completely.

I've asked this on Twitter and there are couple of follow-ups you can find [here](https://twitter.com/uur_oruc/status/1543689286578495488)

Environment:
Browser:  Brave Version 1.40.107, Chromium: 103.0.5060.53 (Official Build)  (x86_64)
Browser 2: Safari Version 15.2 (17612.3.6.1.6)

package.json
```json
{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@makeswift/runtime": "^0.0.22",
    "next": "latest",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@types/node": "17.0.41",
    "@types/react": "18.0.12",
    "typescript": "4.7.3"
  }
}
```

![Screenshot 2022-07-03 at 22 38 28](https://user-images.githubusercontent.com/7689820/177127938-5375ad92-2e86-4957-8f48-e9e9624b576e.png)
![Screenshot 2022-07-03 at 22 38 14](https://user-images.githubusercontent.com/7689820/177127952-493193a1-265d-47e6-a0ce-116f3371a994.png)
![Screenshot 2022-07-03 at 22 37 36](https://user-images.githubusercontent.com/7689820/177127957-795d0710-557b-476f-87b5-237d200ee452.png)

**Comment by migueloller** [comment]
@Ketcap, thanks for opening this issue! I'm looking into it

**Comment by migueloller** [comment]
@Ketcap, just wanted to give you a quick update. It seems that the issue is that Safari (and I'm assuming Brave too, although I haven't tested it yet but will soon) don't want to load `http://localhost:3000` in the iframe because it's served over HTTP and not HTTPS. This can be worked around by configuring the browser to allow for active mixed content. More info in [MDC docs](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content).

I will continue to investigate and will report back with more findings.

**Comment by migueloller** [comment]
Here's the WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=171934

**Comment by Ketcap** [comment]
Thank you @migueloller for investigating and adding into the documentation ☺️🥳
Thanks for all the efforts ☺️
