### ISSUE TITLE
RangeError: Invalid link type "undefined."

### ISSUE THREAD

**Issue by muhammedogz** [makeswift/makeswift#134]
# Problem

When using `Link()` it gives this error. 
```RangeError: Invalid link type "undefined."```

It happens when you use Link() with `Shape` and Component has older data in it..

## Step to reproduce
- Initialize empty project with `npx create-next-app -e cms-makeswift makeswift-app`
- Run `npm i --legacy-peer-deps`
- In `register-components.tsx` Apply this and drag your component on makeswift UI.

```js
import { Link, Shape, Style, TextInput } from "@makeswift/runtime/controls";
import { ReactRuntime } from "@makeswift/runtime/react";

// Register your components here!

function HelloWorld(props: { button: any; className?: string }) {
  console.log("button", props.button);

  return <p {...props}>Hello, world! {props.button} </p>;
}

ReactRuntime.registerComponent(HelloWorld, {
  type: "hello-world",
  label: "Hello, world!",
  props: {
    button: TextInput({ label: "Button Text", defaultValue: "" }),
    className: Style({ properties: Style.All }),
  },
});
```

- After seeing the result, update your `register-components.tsx`  file with this code.

```js
import { Link, Shape, Style, TextInput } from "@makeswift/runtime/controls";
import { ReactRuntime } from "@makeswift/runtime/react";

// Register your components here!

function HelloWorld(props: { button: any; className?: string }) {
  console.log("button", props.button);

  return <p {...props}>Hello, world! {props.button} </p>;
}

ReactRuntime.registerComponent(HelloWorld, {
  type: "hello-world",
  label: "Hello, world!",
  props: {
    button: Shape({
      type: {
        text: TextInput({ label: "Button Text", defaultValue: "" }),
        thisLinkWillCrash: Link(),
      },
    }),
    className: Style({ properties: Style.All }),
  },
});
```

- It will give error. 

It happened me on a global component. And all my pages were giving 500. After couple of hours, I noticed that Link is causing this.

**Comment by fikrikarim** [comment]
Hey thanks a lot for reporting the issue. Looking into this.

**Comment by migueloller** [comment]
Hi @muhammedogz!

Thanks for giving detailed reproduction steps. The problem here is that this is a [breaking change](https://www.makeswift.com/docs/runtime/registering-components#breaking-changes) in the `button` prop. The type of the props changed from

```ts
type Props = {
  button: string
  className: string
}
```

to

```ts
type Props = {
  button: { text: string; thisLinkWillCrash?: { /* ... */ }  }
  className: string
}
```

If there was a string value in `props.button` and then Makeswift attempted to access `props.button.thisLinkWillCrash` it would get `undefined` since `thisLinkWillCrash` does not exist in a string.

What we recommend in situations like these is to create a new component:

```ts
ReactRuntime.registerComponent(HelloWorldV2, {
  type: "hello-world-v2",
  label: "Hello, world! v2",
  props: {
    button: Shape({
      type: {
        text: TextInput({ label: "Button Text", defaultValue: "" }),
        thisLinkWillCrash: Link(),
      },
    }),
    className: Style({ properties: Style.All }),
  },
});
```

And then replace all the occurrences of the old component with the new one. We understand this is less than ideal and we've got plans to fix it. This is a very difficult problem, though, because it's pretty hard to know the different combinations of props people will use and we have to provide APIs that let them seamlessly migrate from one type to another.

That being said, the entire page crashing when an error like this is encountered is now the user experience that we want so we'll work on adding error boundaries to components so that when something like this happens you can still select the errored component and either delete it or clear its props. Clearing the props might even fix the issue since that will "reset" the data and so the old TextInput data shouldn't conflict with the new Shape data.

If you want a quick solution for now, you can remove the controls so the page doesn't crash, select and remove the component, and then you can drop it again with new props.

I'll leave this issue open until we add error boundaries, though!

**Comment by migueloller** [comment]
@muhammedogz, I ran the reproduction steps you provided locally and the error I'm seeing is the following:

```
Error: Objects are not valid as a React child (found: object with keys {text, thisLinkWillCrash}). If you meant to render a collection of children, use an array instead.
```

This is because `{props.button}` is being interpolated in the React component:

```tsx
<p {...props}>Hello, world! {props.button} </p>
```

If you remove the `props.button` interpolation, the error should be resolved. i.e.,:

```tsx
<p {...props}>Hello, world!</p>
```

So in this specific scenario, you have to make sure the "new" component uses the new Link prop value properly. That being said, I'm still working on adding the error boundaries so that errors like these are more easily recoverable 😄

**Comment by muhammedogz** [comment]
> Hi @muhammedogz!
> 
> Thanks for giving detailed reproduction steps. The problem here is that this is a [breaking change](https://www.makeswift.com/docs/runtime/registering-components#breaking-changes) in the `button` prop. The type of the props changed from
> 
> ```ts
> type Props = {
>   button: string
>   className: string
> }
> ```
> 
> to
> 
> ```ts
> type Props = {
>   button: { text: string; thisLinkWillCrash?: { /* ... */ }  }
>   className: string
> }
> ```
> 
> If there was a string value in `props.button` and then Makeswift attempted to access `props.button.thisLinkWillCrash` it would get `undefined` since `thisLinkWillCrash` does not exist in a string.
> 
> What we recommend in situations like these is to create a new component:
> 
> ```ts
> ReactRuntime.registerComponent(HelloWorldV2, {
>   type: "hello-world-v2",
>   label: "Hello, world! v2",
>   props: {
>     button: Shape({
>       type: {
>         text: TextInput({ label: "Button Text", defaultValue: "" }),
>         thisLinkWillCrash: Link(),
>       },
>     }),
>     className: Style({ properties: Style.All }),
>   },
> });
> ```
> 
> And then replace all the occurrences of the old component with the new one. We understand this is less than ideal and we've got plans to fix it. This is a very difficult problem, though, because it's pretty hard to know the different combinations of props people will use and we have to provide APIs that let them seamlessly migrate from one type to another.
> 
> That being said, the entire page crashing when an error like this is encountered is now the user experience that we want so we'll work on adding error boundaries to components so that when something like this happens you can still select the errored component and either delete it or clear its props. Clearing the props might even fix the issue since that will "reset" the data and so the old TextInput data shouldn't conflict with the new Shape data.
> 
> If you want a quick solution for now, you can remove the controls so the page doesn't crash, select and remove the component, and then you can drop it again with new props.
> 
> I'll leave this issue open until we add error boundaries, though!

Yes you are right, I run again this steps again in my local test. And it seems it is just a React rendering issue 🤗

I overcame this problem in my main project with removing those props, and cleaning the component on Makeswift UI and re implement without using `Shape`. I will try to reuse the same structure in my main projecct to reproduce. Thanks 😇
